import { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import api from '../api/axios';

export default function MealsAndPolls() {
  const [polls, setPolls] = useState([]); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ question: '', options: '', deadline: '', scheduledDate: '' });
  const load = () => api.get('/polls').then((r) => setPolls(r.data)).catch(() => setMessage('Unable to load polls.'));
  useEffect(() => { load(); }, []);
  const create = async (e) => { e.preventDefault(); const options = form.options.split('\n').map((v) => v.trim()).filter(Boolean); if (options.length < 2) return setMessage('Enter at least two options.'); try { await api.post('/polls', { ...form, options }); setForm({ question: '', options: '', deadline: '', scheduledDate: '' }); setMessage('Poll created.'); load(); } catch (err) { setMessage(err.response?.data?.message || 'Unable to create poll.'); } };
  const close = async (id) => { try { await api.post(`/polls/${id}/close`); setMessage('Poll closed and winning meal published.'); load(); } catch (err) { setMessage(err.response?.data?.message || 'Unable to close poll.'); } };
  return <Layout title="Meals & Voting"><div className="grid lg:grid-cols-2 gap-6"><form className="card space-y-3" onSubmit={create}><h2 className="text-lg font-bold">Create Meal Poll</h2><p className={message.includes('Unable') || message.includes('at least') ? 'text-red-600 text-sm' : 'text-green-600 text-sm'}>{message}</p><input className="input-field" placeholder="Poll question" value={form.question} required onChange={(e) => setForm({...form,question:e.target.value})}/><textarea className="input-field" rows="4" placeholder={'One option per line\nPaneer\nAloo\nMix Veg'} value={form.options} required onChange={(e) => setForm({...form,options:e.target.value})}/><label className="block text-sm">Deadline<input className="input-field mt-1" type="datetime-local" required value={form.deadline} onChange={(e) => setForm({...form,deadline:e.target.value})}/></label><label className="block text-sm">Meal date<input className="input-field mt-1" type="date" required value={form.scheduledDate} onChange={(e) => setForm({...form,scheduledDate:e.target.value})}/></label><button className="btn-primary">Create Poll</button></form><section className="space-y-4"><h2 className="text-lg font-bold">Poll Results</h2>{polls.length ? polls.map((p) => { const winner = p.options.find((o) => o._id === p.winningOptionId); return <article className="card" key={p._id}><div className="flex justify-between gap-3"><h3 className="font-bold">{p.question}</h3><span className="text-sm">{p.status}</span></div><div className="mt-3 space-y-1">{p.options.map((o) => <p key={o._id}>{o.text}: <b>{o.votes}</b> votes</p>)}</div>{p.status === 'Closed' ? <p className="mt-3 text-green-700">Winner: {winner?.text || p.publishedMealTitle || 'No votes'}</p> : <button className="mt-3 btn-secondary" onClick={() => close(p._id)}>Close poll & publish winner</button>}</article>; }) : <div className="card text-gray-500">No polls created yet.</div>}</section></div></Layout>;
}
